flcdrg/au-packages

ozcode-vs2017/ozcode-vs2017.nuspec, ozcode-vs2017/tools/chocolateyinstall.ps1
- Avoid downloading vsix to tools directory (otherwise it gets included in the package)
=> OzCode VS2017 3.1.0.3913

sqltoolbelt/sqltoolbelt.nuspec, sqltoolbelt/tools/chocolateyinstall.ps1
* Update documentation.
* Update last modified version so that package is actually downloaded from redgate instead of FTP.
=> Allow for users to specify the products they want to install.

azure-pipelines-agent/tools/chocolateyinstall.ps1
=+ is not a valid operation, should read +=
=> fixed '=+' typo

SqlSearch/SqlSearch.nuspec, SqlSearch/tools/chocolateyInstall.ps1, SqlSearch/update.ps1, redgate/common.ps1
- Previously hosted at https://github.com/sumo300/chocolatey-sqlsearch
- Add update.ps1
Thanks to @sumo300 for previously managing this package
=> Copy SqlSearch from @sumo300

beyondcompare/tools/chocolateyInstall.ps1, beyondcompare/update.ps1
Add chinese language version for beyondcompare
=> add zh version for beyondcompare

azure-pipelines-agent/azure-pipelines-agent.nuspec, azure-pipelines-agent/tools/chocolateyinstall.ps1
Minor update to latest azure-pipeline-agent package
=> Update to 2.160.1

azure-pipelines-agent/azure-pipelines-agent.nuspec, azure-pipelines-agent/tools/chocolateyinstall.ps1
=> Added SSL parameter support for azure-pipelines-agent

azure-pipelines-agent/azure-pipelines-agent.nuspec, azure-pipelines-agent/tools/chocolateyinstall.ps1
Adding the /CollectionName parameter, was unable to install and configure agent without it.
=> Add /CollectionName parameter in chocolateyinstall.ps1

azure-pipelines-agent/azure-pipelines-agent.nuspec, azure-pipelines-agent/tools/chocolateyinstall.ps1
I add proxy arguments to azure-pipelines-agent, but have no chance to test package. Can you do this?
=> fixes #85 - https://github.com/flcdrg/au-packages/issues/85

microsoft-teams.install/microsoft-teams.install.nuspec, microsoft-teams.install/tools/chocolateyinstall.ps1
=> Add package parameters to microsoft-teams.install

iguana.install/iguana.install.nuspec, iguana.install/tools/chocolateyinstall.ps1, iguana.install/tools/chocolateyuninstall.ps1, iguana.install/update.ps1, iguana.portable/iguana.portable.nuspec, iguana.portable/tools/chocolateyinstall.ps1, iguana.portable/update.ps1
- Fix portable
- Fix install (as now it's a .zip with the .exe inside)
=> Update Iguana packages

sql-server-management-studio/sql-server-management-studio.nuspec, sql-server-management-studio/tools/chocolateyinstall.ps1
=> [sql-server-management-studio] Support parameter path to EXE

microsoft-teams.install/microsoft-teams.install.nuspec, microsoft-teams.install/tools/chocolateyinstall.ps1
Microsoft-Teams.install | Add ALLUSER option for machine-wide VDI
=> Teams: ALLUSER

keepass-rpc/tools/chocolateyinstall.ps1, keepass-rpc/tools/chocolateyuninstall.ps1, keepass-rpc/tools/common.ps1
=> Look up keepass plugin path for keepass-rpc

sql-server-2017-cumulative-update/tools/chocolateyinstall.ps1
=> Fix for #111 (CU25 chocolatey update)

windows-admin-center/tools/chocolateyinstall.ps1, windows-admin-center/windows-admin-center.nuspec
add the option to disable the restart of winrm with admin center install.
=> Restart winrm

beyondcompare-integration/README.md, beyondcompare-integration/beyondcompare-integration.nuspec, beyondcompare-integration/tools/chocolateyinstall.ps1
Extended the script to integrate Beyond Compare with the [Fork Git client](https://fork.dev) if it is installed.
=> Implement settings update for Fork.dev on Windows

pingplotter/pingplotter.nuspec, pingplotter/tools/chocolateyinstall.ps1
Update version & checksum to the latest.
=> update pingplotter version & checksum

sql-server-express/sql-server-express.nuspec, sql-server-express/tools/chocolateybeforemodify.ps1, sql-server-express/tools/chocolateyinstall.ps1, sql-server-express/tools/chocolateyuninstall.ps1
=> Update sql-server-express to 2022

ReSharper/ReSharper.nuspec, ReSharper/tools/chocolateyinstall.ps1, ReSharperCpp/ReSharperCpp.nuspec, ReSharperCpp/tools/chocolateyinstall.ps1, dotCover/dotCover.nuspec, dotCover/tools/chocolateyinstall.ps1, dotMemory/dotMemory.nuspec, dotMemory/tools/chocolateyinstall.ps1, dotPeek/dotPeek.nuspec, dotPeek/tools/chocolateyinstall.ps1, dotTrace/dotTrace.nuspec, dotTrace/tools/chocolateyinstall.ps1, resharper-ultimate-all/tools/chocolateyinstall.ps1, teamCityAddin/teamcityaddin.nuspec, teamCityAddin/tools/chocolateyinstall.ps1
=> Add /PerMachine to other JetBrains tools

sql-server-2022-cumulative-update/tools/chocolateyinstall.ps1
=> Fix sql server version mentioned

teamcity/tools/chocolateyInstall.ps1, teamcity/update-common.ps1, teamcity/update.ps1
- Stop using ChocolateyPackageVersion
- Fixes
=> fix teamcity

mirth-administrator-launcher.install/mirth-administrator-launcher.install.nuspec, mirth-administrator-launcher.install/tools/chocolateyinstall.ps1, mirth-administrator-launcher/mirth-administrator-launcher.nuspec
Hello - I install mirth via chocolatey and would like to see it updated. Hope this helps. Thanks for maintaining it!
=> update mirth-administrator-launcher to v1.4.1

lenovo-thinkvantage-system-update/update.ps1
=> Improve lenovo version detection

microsoft-teams-new-bootstrapper/microsoft-teams-new-bootstrapper.nuspec, microsoft-teams-new-bootstrapper/tools/chocolateyinstall.ps1
Closes #175 
I had some time to implement this myself.
=> SystemWide Meeting Add-in Installation

consul/consul.nuspec, consul/tools/chocolateyInstall.ps1, consul/tools/chocolateyUninstall.ps1, consul/update.ps1
Hi,
I decided to implement what I want in #180 and I'm pretty satisfied with the result. Please review and merge, thanks!
Fixes #180
=> Consul: new package params, au improvements

microsoft-teams-new-bootstrapper/tools/chocolateyuninstall.ps1
I added a uninstall file because on the default the uninstall doesn't remove MS Teams 2
=> Add Uninstall file

microsoft-teams-new-bootstrapper/tools/chocolateyinstall.ps1
Added a section to ensure a $teamsVersion is found. I had some failures showing the meeting path with no $teamsVersion. This folder method is how I was doing it up to now, but I'd like to use chocolatey.
=> Adding section to ensure we get a Teams Version

ubiquiti-unifi-controller/tools/unifi-uninstall.ahk, ubiquiti-unifi-controller/tools/unifi-upgrade.ahk, ubiquiti-unifi-controller/ubiquiti-unifi-controller.nuspec
=> Update UniFi Controller to use AHK v2

ubiquiti-wifiman-desktop/tools/chocolateyinstall.ps1, ubiquiti-wifiman-desktop/ubiquiti-wifiman-desktop.nuspec
=> Update wifiman to 1.1.3
